### PR TITLE
Nested Support

### PR DESCRIPTION
**Pull request by nmccready**
Piggy backed more work on top of #28

### CODE REVIEW

**Comment by danactive** [comment]
Good test coverage, I'm also hoping for this to be merged it.

@caseypt Poke

**Comment by mvl22** [comment]
What remains to be done here? I see there is a conflict.

**Comment by viktorstrate** [comment]
Please merge this pull request, this feature is really needed

**Comment by nmccready** [comment]
I will fix the conflicts; but I doubt any one will merge this its been almost 2 years.

**Comment by nmccready** [comment]
Conflicts gone and merged.

**Comment by caseycesari** [comment]
Sorry for the delay. Thanks for the updated PR. I had intentions of doing a more minimal implementation of this, but I clearly haven't done that. I'll merge this and release a new version this weekend. Thanks again for the PR.

**Comment by caseycesari** [comment]
Merged and released with v0.5.0. Again, apologies for the long delay.

**Pull request merged**
