### PR TITLE
modify crs property

### PR DESCRIPTION
**Pull request by DemersM**
Allow user to define the crs by his own to allow link crs and name crs as well

### CODE REVIEW

**Comment by caseypt** [comment]
Thanks for the PR! This is a good idea that I'm in favor of.

I'd like to update the tests and documentation before merging, though.

I'll get to that in the next week or so if you don't.

**Comment by caseypt** [comment]
Superseded by #19.

**Comment by DemersM** [comment]
Thats perfect! Thank you!

**Comment by caseypt** [comment]
@DemersM I just pushed v0.3.0 to npm which has this feature. Thanks again.

**Pull request closed without merging**
