### PR TITLE
Adding undefined/null check for `container.lat` scenarios.

### LINKED ISSUE #47: cannot call hasOwnProperty of null on itemClone
When passing data through to this tool, there was a null value that was causing an error on lines 233 and 251.  A simple undefined check should be a nice safeguard to prevent the process from crashing in this scenario.

### PR DESCRIPTION
**Pull request by hparkertt**
Resolves #47

### CODE REVIEW

**Comment by hparkertt** [comment]
@caseycesari Any thoughts on taking a look at this?  631ef53 should be straightforward enough.  f9e7f50 isn't really necessary, it's just a quick fix for the jshint task.

**Comment by caseycesari** [comment]
@hparkertt Hey, thanks for the reminder, and the fix. Any chance you could add a test? If not, I can add one this week and get this released. Thanks.

**Comment by hparkertt** [comment]
@caseycesari The tests are in, but I noticed a limitation of GeoJSON that I might try and fix right off.  The limitation is that you cannot specify multiple geometry mappings in the param object that do not have similar nested property paths.  The buildGeom function returns false at [line 234](https://github.com/caseycesari/GeoJSON.js/blob/master/geojson.js#L234) and at [line 252](https://github.com/caseycesari/GeoJSON.js/blob/master/geojson.js#L252), not allowing the [params.geom loop](https://github.com/caseycesari/GeoJSON.js/blob/master/geojson.js#L181) to continue and attempt to find a matching nested property path with a different geometry type.

**Comment by hparkertt** [comment]
Hi @caseycesari I've added a few issues that can be labeled as 'enhancements'.  I probably could have done it a little cleaner, but I've created pull requests for each issue.  Overall, here is what I've done:

- I resolved #47 here
- I created #49 and resolved that with #51 
- I resolved #34 with #52 
- I created #50 and resolved that with #53 

At this point we should focus discussion for each issue in it's own page; I only listed this out here because this is where our conversation started.  This library is a really great, simple tool, and I hope these changes help give it a little extra functionality!

Thanks!

**Comment by caseycesari** [comment]
@hparkertt Oh wow! Thanks for all of these PRs. I'm going to try and get through these over the next couple days.

**Comment by caseycesari** [comment]
This looks good. Merging.

**Pull request merged**
